version: "3.3"

services:
  mongo:
    image: mongo
    volumes:
      - ./data-db:/data/db
    environment:
      - MONGODB_DATABASE="data"
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_BASICAUTH_USERNAME="julien"
      - ME_CONFIG_BASICAUTH_PASSWORD="\%cJm7:{#4B"+8jj"
    ports:
      - 8081:8081
