@startuml

title Mob party !

actor Mober1 as mober1
boundary "mob-timer" as gui
control "mob-backend" as api
boundary "mob-timer" as gui2
actor Mober2 as mober2

mober1 -> gui: connect
activate gui
gui --> mober1
mober1 -> gui: create Mob
activate gui
gui ->> api: create Mob
activate api
api --> gui: saved
deactivate api
gui --> mober1
deactivate gui

mober2 -> gui2: connect
activate gui2
gui2 -> api: get Mob
activate api
api --> gui2
deactivate api
gui2 --> mober2

mober1 -> gui: start
gui -> api: update Mob
activate api
api -> gui2: notify Mob updated
api --> gui
deactivate api

gui --> mober1: counter started
gui2 --> mober2: counter started

mober2 -> gui2: pause
activate gui2
gui2 -> api: update Mob
api -> gui: notify Mob updated
api --> gui2
deactivate gui2

@enduml