server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mob-programming

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG