### GET MOB

GET {{timer-api}}/mob-programming/api/mobs/b49326b5-beaf-46d8-971f-915ce9cac311

### CREATE MOB
POST {{timer-api}}/mob-programming/api/mobs HTTP/1.1
content-type: application/json

{
  "name": "DreamTeam",
  "duration": 18,
  "mobers": ["Joe", "Jimi", "Elisa"]
}

### CREATE MOB
POST {{timer-api}}/mob-programming/api/mobs HTTP/1.1
content-type: application/json

{
  "name": "lesDaltons",
  "duration": 22,
  "mobers": ["Joe", "Jack", "William", "Averell"]
}

### UPDATE MOB

PUT {{timer-api}}/mob-programming/api/mobs/2dc17d4f-3c26-4404-befd-aa6013744d05

{
  "id": "2dc17d4f-3c26-4404-befd-aa6013744d05",
  "name": "lesDaltons",
  "duration": 30,
  "mobers": [
    "Joe",
    "Jack",
    "William",
    "Averell"
  ]
}

### START MOB

PUT {{timer-api}}/mob-programming/api/mobs

{
  "name": "DreamTeam",
  "duration": 15,
  "round": {
    "timerStartTimestamp": "16:55",
    "started": true
  },
  "mobers": ["Joe", "Jimi", "Elisa"]
}

### DELETE MOB

DELETE {{timer-api}}/mob-programming/api/mobs/2dc17d4f-3c26-4404-befd-aa6013744d05

### LIST ALL MOBS

GET {{timer-api}}/mob-programming/api/mobs

### TAIL MOBS

GET {{timer-api}}/mob-programming/api/mobs/tail/DreamTeam
Accept: text/event-stream

###
