name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mob-timer-deploy:
    runs-on: ubuntu-latest
    env:
      appName: mob-timer
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check changes
        run: |
          GITDIFF=$(git diff --name-only HEAD^ HEAD | grep -E -- '${{ env.appName }}' | tr -d '[:space:]')
          if [ "$GITDIFF" == "" ]; then
            echo "No code changes, skipped"
            exit 0
          fi
          echo "${{ env.appName }} will be build and published"
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Build
        run: |
          cd ${{ env.appName }}
          npm install
          npm run build
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ env.appName }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
